name: 첫번째 github Action
on:
  push:
    branches:
      - main

jobs:
  My-Action-Job:
    runs-on: ubuntu-latest
    steps:
      - name: First-Step - 리눅스 명령어
        run: |
          echo "Hello World"
          echo "Github Action"
          pwd
          ls -al

      - name: Second-Step - Github 환경변수
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo ${{ secrets.MY_SECRET_DATA }}
          echo  ${{ secrets.AWS_SERVER_IP }}